### FedEx API 認證測試
### 使用測試環境端點

POST https://apis-sandbox.fedex.com/oauth/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id={{FEDEX_CLIENT_ID}}&client_secret={{FEDEX_CLIENT_SECRET}}

###

### 使用生產環境端點 (如果需要)
# POST https://apis.fedex.com/oauth/token
# Content-Type: application/x-www-form-urlencoded
# 
# grant_type=client_credentials&client_id={{$FEDEX_CLIENT_ID}}&client_secret={{$FEDEX_CLIENT_SECRET}}

###

### 測試追蹤 API (需要先獲取 access_token)
# POST https://apis-sandbox.fedex.com/track/v1/trackingnumbers
# Authorization: Bearer YOUR_ACCESS_TOKEN_HERE
# Content-Type: application/json
# 
# {
#   "includeDetailedScans": true,
#   "trackingInfo": [
#     {
#       "trackingNumberInfo": {
#         "trackingNumber": "123456789012"
#       }
#     }
#   ]
# }
